stages:
  - scan
  - push

python-src-format:
  stage: scan
  tags:
    - docker
  image: python:3.8
  script:
    - pip install pipenv
    - pipenv install --dev --skip-lock
    - pipenv run black --check src/ && pipenv run isort --check src/
    - pipenv run black --check test/ && pipenv run isort --check test/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

python-src-lint:
  stage: scan
  tags:
    - docker
  image: python:3.8
  script:
    - pip install pipenv
    - pipenv install --dev --skip-lock
    - pipenv run flake8 src/ && pipenv run mypy src/
    - pipenv run flake8 test/ && pipenv run mypy test/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

python-test:
  stage: scan
  tags:
    - docker
  image: python:3.8
  script:
    - pip install pipenv
    - pipenv install --dev --skip-lock
    - pipenv run pytest --cov=src test/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'


coverage:
  stage: scan
  tags:
    - docker
  image: python:3.8
  script:
    - pip install pipenv
    - pipenv install --dev --skip-lock
    - pipenv run pytest --runslow --cov=src --cov-report term --cov-report xml:coverage.xml test/
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report: 
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual

sync-repositories:
  stage: push
  tags:
    - docker
  image: bitnami/git
  script:
    # prepare remote repositories
    - git remote set-url origin https://gitlab-ci-token:$GITLAB_TOKEN@${CI_REPOSITORY_URL##*@}
    - git config remote.github.url >&- && git remote set-url github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/fixstars/amplify-benchmark-test.git || git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/fixstars/amplify-benchmark-test.git
    - git config user.email "noreply@fixstars.com"
    - git config user.name "GitLab Bot"
    - git fetch github main
    - git fetch origin main develop
    - git switch develop
    - git reset --hard origin/develop
    - git clean -xfd
    # rebase and push
    - git status
    - git rebase github/main
    - git push origin develop
    - git push origin develop:main
    - git push github develop:main
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"'
