[tool.black]
line-length = 120

[tool.isort]
profile = "black"
include_trailing_comma = true
line_length = 120
multi_line_output = 3

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
